---
- name: My first playbook
  hosts: localhost

  tasks:
  - name: deploy software from aptitude repository
    apt:
      name: bastet    ## installs bastet (tetris)
      state: present  ## INSTALL 
    become: yes       ## run in sudo mode
    register: results # save JSON object sent back

  - name: print to the screen our results variable
    debug:
      var: results
